name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check-composer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none
          tools: composer:v2
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate composer.json
        run: composer validate

  php-linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - 8.2
          - 8.3
          - 8.4
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: none

      - name: PHP lint
        run: "find *.php Classes Configuration -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l"

  coding-guideline:
    runs-on: ubuntu-latest
    needs:
      - check-composer
    steps:
      - uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          coverage: none
          tools: composer:v2
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: composer install --no-progress --no-interaction --optimize-autoloader

      - name: Coding Guideline
        run: ./vendor/bin/ecs check

  code-quality:
    runs-on: ubuntu-latest
    needs:
      - check-composer
    strategy:
      matrix:
        include:
          - php-version: '8.2'
            typo3-version: '^13.4'
          - php-version: '8.3'
            typo3-version: '^13.4'
          - php-version: '8.4'
            typo3-version: '^13.4'
    steps:
      - uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: none
          tools: composer:v2
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies with expected TYPO3 version
        run: composer require --no-progress --no-interaction --optimize-autoloader "typo3/cms-core:${{ matrix.typo3-version }}"

      - name: PHPStan
        run: ./vendor/bin/phpstan
